import { auth, db } from "./firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { doc, getDoc, collection, addDoc, serverTimestamp, onSnapshot, deleteDoc, updateDoc, query, orderBy, where } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const form=document.querySelector("#bookForm"), booksTable=document.querySelector("#adminBooks"), reviewsTable=document.querySelector("#adminReviews");
onAuthStateChanged(auth,async user=>{if(!user)return location.href="auth.html";const u=await getDoc(doc(db,"users",user.uid));if(u.data()?.role!=="admin")return location.href="index.html";
onSnapshot(query(collection(db,"books"),orderBy("createdAt","desc")),snap=>{booksTable.innerHTML=snap.docs.map(d=>{const b=d.data();return `<tr><td><strong>${esc(b.title||"")}</strong><small>${esc(b.author||"")}</small></td><td>${esc(b.author||"")}</td><td>★ ${Number(b.rating||0).toFixed(1)}</td><td><button class="btn danger small" data-delete-book="${d.id}">Удалить</button></td></tr>`}).join("");booksTable.querySelectorAll("button[data-delete-book]").forEach(btn=>btn.onclick=async()=>{if(confirm("Удалить книгу?"))await deleteDoc(doc(db,"books",btn.dataset.deleteBook));});});
onSnapshot(query(collection(db,"reviews"),orderBy("createdAt","desc")),snap=>{reviewsTable.innerHTML=snap.docs.map(d=>{const r=d.data();return `<tr><td>${esc(r.bookId)}</td><td>${Number(r.rating||0)}/5</td><td>${esc((r.text||"").slice(0,90))}</td><td><button class="btn danger small" data-delete-review="${d.id}">Удалить</button></td></tr>`}).join("");reviewsTable.querySelectorAll("button[data-delete-review]").forEach(btn=>btn.onclick=async()=>{if(confirm("Удалить отзыв?")){const reviewSnap=await getDoc(doc(db,"reviews",btn.dataset.deleteReview));const bookId=reviewSnap.data()?.bookId;await deleteDoc(doc(db,"reviews",btn.dataset.deleteReview));if(bookId)await recalcBook(bookId);}});});});
form.addEventListener("submit",async e=>{e.preventDefault();const title=document.querySelector("#bookTitle").value.trim(),author=document.querySelector("#bookAuthor").value.trim(),category=document.querySelector("#bookCategory").value,year=Number(document.querySelector("#bookYear").value)||null,imageUrl=document.querySelector("#bookImage").value.trim(),description=document.querySelector("#bookDescription").value.trim();await addDoc(collection(db,"books"),{title,titleLower:title.toLowerCase(),author,category,year,imageUrl,description,rating:0,reviewCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});form.reset();document.querySelector("#bookMessage").textContent="Книга добавлена.";});
async function recalcBook(bookId){const {getDocs}=await import("https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js");const snap=await getDocs(query(collection(db,"reviews"),where("bookId","==",bookId)));const vals=snap.docs.map(d=>Number(d.data().rating||0));const rating=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;await updateDoc(doc(db,"books",bookId),{rating:Number(rating.toFixed(1)),reviewCount:vals.length,updatedAt:serverTimestamp()});}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
